### ISSUE TITLE
[1.11.2] NoSuchMethod

### ISSUE THREAD

**Issue by Terpo** [LETU-Team/BearWithMe#1]
Log: https://gist.github.com/Terpo/853f4643ffe61b49a43d73dc6a69a298
BWM v1.2 for 1.11.2
Forge 13.20.0.2230

Just added it for testing and it didn't survive the init phase^^

**Comment by Cazsius** [comment]
We currently do not support 1.11.2 for BearWithMe

**Comment by Terpo** [comment]
You should give the port to 1.11.2 a try. 
I did finish the update in a few minutes but there were some problems with the forge biome dictionary :/
http://www.minecraftforge.net/forum/topic/53441-1112-getbiomes-not-returning-anything/
I used the solution from the third post to get it working. Here everything you need:

for gradle:
mc_version=1.11.2
forge_version=13.20.0.2228
mappings_version=snapshot_20161220

this.worldObj changes to this.world

and for your common proxy I changed the init() function
https://gist.github.com/Terpo/08b58c133c70c03ea62fcf2790fd2308

thats all :)

**Comment by Cazsius** [comment]
I will be porting to 1.11.2 once the new content update is released, I know i could port it in 5 minutes, but I don't want to. I am waiting on some things to release a new content update, which is basically a rewritten form, from there it will be ported to 1.11.2

**Comment by Terpo** [comment]
K, thats a word. But for now I've got something functional. ^^

**Comment by Cazsius** [comment]
If you want to know when an official update or port is done, join my discord here: https://discord.gg/JZzD4EQ
