### ISSUE TITLE
Suggestion : A config file for next version pls!

### ISSUE THREAD

**Issue by alxcool** [LETU-Team/BearWithMe#4]
Hello! I really like the concept of this mod. I have a suggestion for the next update. Could you provide configuration options? Either those that can be modified during the game, or those that are available in the game / config directory.

For example, I wish I could change the rate of appearance of bears. From my perspective, 2-3 family by chunks is way too much. Also it could be nice to be able to modify the damage caused by the beast and the distance of pursuit.

My configuration: The old minecraft launcher in 1.12.2, forge 2603, windows 7 64b, 4gb ram reserved, Solo players on a game of more than 100 mods without packs.

**Comment by CatastropheBlack** [comment]
Config file is now available in release 1.12.2-1.3.
